ARG STICKY_VERSION=3.4
FROM debian:bookworm

ENV APP_VERSION=3.4 \
    DEBIAN_FRONTEND=noninteractive \
    REPO=pbs-docker \
    IMAGE=pbs

LABEL org.opencontainers.image.source=https://github.com/Neomediatech/${REPO} \
      org.opencontainers.package.name=proxmox-backup-server

ARG BIN_SOURCE=https://github.com/Neomediatech/assets/raw/refs/heads/main/bin
ADD --chmod=777 ${BIN_SOURCE}/tini \
                ${BIN_SOURCE}/http \
                ${BIN_SOURCE}/curl \
                ${BIN_SOURCE}/wget \
                /usr/local/bin/

ADD --chmod=777 ${BIN_SOURCE}/gosu \
                /usr/local/bin/

# workaround to make PBS install
RUN ln -s /bin/true /usr/bin/systemctl && \
    echo exit 0 > /usr/sbin/policy-rc.d && \
    # install some needed package
    apt-get update && \
    apt-get -y --no-install-recommends --no-install-suggests install ca-certificates openssl rsyslog && \
    apt-get clean && \
    rm -rf /var/lib/apt/lists/* /tmp/* /var/tmp/*

# add PBS repository
RUN wget https://enterprise.proxmox.com/debian/proxmox-release-bookworm.gpg -O /etc/apt/trusted.gpg.d/proxmox-release-bookworm.gpg && \
    echo "deb http://download.proxmox.com/debian/pbs bookworm pbs-no-subscription" > /etc/apt/sources.list.d/pbs-free.list

# install PBS
RUN apt-get update && \
    apt-get install -y -V --no-install-recommends proxmox-backup-server=3.4.3-1 proxmox-backup-docs=3.4.3-1 && \
    apt-get clean && \
    rm -rf /var/lib/apt/lists/* /tmp/* /var/tmp/* /usr/share/doc/proxmox-backup* /etc/apt/sources.list.d/pbs-enterprise.list

# disable kernel logging module and log everything to stdout
RUN sed -i '/.*imklog.*/d' /etc/rsyslog.conf && \
    echo '*.* -/proc/1/fd/1' >> /etc/rsyslog.conf

COPY entrypoint.sh /

# create some dir and change permissions/owner
RUN mkdir -p /etc/proxmox-backup /var/log/proxmox-backup /var/lib/proxmox-backup /var/log/proxmox-backup/tasks/ /run/proxmox-backup && \
    chsh -s /bin/bash backup && \
    usermod -a -G backup root && \
    usermod -g backup root && \
    usermod -aG sudo backup && \
    chown -R backup:backup /etc/proxmox-backup && \
    chown -R backup:backup /var/log/proxmox-backup && \
    chown -R backup:backup /var/lib/proxmox-backup && \
    chmod -R 700 /etc/proxmox-backup && \
    chmod +x /entrypoint.sh

# add tini support to avoid zombies (as Postfix does)
ENTRYPOINT [ "tini", "--", "/entrypoint.sh" ]

CMD ["/bin/bash"]

