name: Test Email

on:
  workflow_dispatch:

jobs:
  send-email:
    runs-on: ubuntu-latest

    steps:
      - name: Create fake HTML report
        run: echo "<html><body><h1>Report di test</h1></body></html>" > report.html

      - name: Create Python script
        run: |
          echo "import smtplib" > send_email.py
          echo "import ssl" >> send_email.py
          echo "from email.message import EmailMessage" >> send_email.py
          echo "from pathlib import Path" >> send_email.py
          echo "" >> send_email.py
          echo "msg = EmailMessage()" >> send_email.py
          echo "msg['Subject'] = '📧 Test Email da GitHub Actions'" >> send_email.py
          echo "msg['From'] = '${{ secrets.SMTP_FROM }}'" >> send_email.py
          echo "msg['To'] = '${{ secrets.SMTP_TO }}'" >> send_email.py
          echo "msg.set_content('Questo è un test di invio email da GitHub Actions.')" >> send_email.py
          echo "" >> send_email.py
          echo "report_path = Path('report.html')" >> send_email.py
          echo "if report_path.exists():" >> send_email.py
          echo "    with report_path.open('rb') as f:" >> send_email.py
          echo "        msg.add_attachment(f.read(), maintype='text', subtype='html', filename='report.html')" >> send_email.py
          echo "" >> send_email.py
          echo "context = ssl.create_default_context()" >> send_email.py
          echo "with smtplib.SMTP_SSL('${{ secrets.SMTP_HOST }}', int('${{ secrets.SMTP_PORT }}'), context=context) as smtp:" >> send_email.py
          echo "    smtp.login('${{ secrets.SMTP_USER }}', '${{ secrets.SMTP_PASSWORD }}')" >> send_email.py
          echo "    smtp.send_message(msg)" >> send_email.py

      - name: Run Python script
        run: python3 send_email.py
